package com.stockmgt.entities;
// Generated 10 d�c. 2018 14:48:45 by Hibernate Tools 5.3.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java.
 */
@Entity
@Table(name = "product", catalog = "stockmanagement")
public class Product implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Category category;
	private String productName;
	private String productCode;
	private Integer stock;
	private Double priceHt;
	private Double priceTtc;
	private Date createdAt;
	private Date updatedAt;

	public Product() {
	}

	public Product(String productName) {
		this.productName = productName;
	}

	public Product(Category category, String productName, String productCode, Integer stock, Double priceHt,
			Double priceTtc, Date createdAt, Date updatedAt) {
		this.category = category;
		this.productName = productName;
		this.productCode = productCode;
		this.stock = stock;
		this.priceHt = priceHt;
		this.priceTtc = priceTtc;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "product_name", nullable = false, length = 100)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "product_code", length = 45)
	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	@Column(name = "stock")
	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	@Column(name = "price_ht", precision = 22, scale = 0)
	public Double getPriceHt() {
		return this.priceHt;
	}

	public void setPriceHt(Double priceHt) {
		this.priceHt = priceHt;
	}

	@Column(name = "price_ttc", precision = 22, scale = 0)
	public Double getPriceTtc() {
		return this.priceTtc;
	}

	public void setPriceTtc(Double priceTtc) {
		this.priceTtc = priceTtc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Product other = (Product) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Product [name=" + productName + ", price=" + priceTtc + "]";
	}

}
